[package]
name = "rest"
version = "0.1.0"
authors = ["Marcin <m.liebiediew@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", features=["openssl"] }
openssl = "0.10.33"
serde = "1.0.125"
serde_json = "1.0.64"
